backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
site_url: https://steeplechaseplaza.com
media_folder: static/images/
public_folder: static/images/

collections:
  - name: "business"
    label: "Business" # Used in the UI
    folder: "_posts/businesses" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    identifier_field: store
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "businessData"}
      - {label: store, name: store, widget: "string"}
      - {label: status, name: status, widget: "boolean"}
      - {label: location, name: location, widget: "string" }
      - {label: Google Maps Link, name: googleMapsLink, widget: "string", required: false}
      - {label: Telephone, name: telephone, widget: "string", required: false}
      - {label: Website, name: website, widget: "string", required: false}
      - {label: Storefront image, name: storeFrontImage, widget: "image", required: false}
      - {label: info, name: info, widget: "string", required: false}

  - name: "coupons"
    label: "Coupons"
    folder: "_posts/coupons"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "coupon"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "start date", widget: "date"}
      - {label: "End Date", name: "end date", widget: "date"}
      - {label: "Info", name: "info", widget: "markdown"}
      - {label: "Coupon Image", name: "coupon image", widget: "image", required: false}

  - name: "events"
    label: "Events"
    folder: "_posts/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "events"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "start date", widget: "date"}
      - {label: "Info", name: "info", widget: "markdown"}
      - {label: "Event Image", name: "event image", widget: "image", required: false}