backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: /images/uploads # Media files will be stored in the repo under images/uploads
public_folder: /images
collections:
  - name: "businesses"
    label: "Businesses" # Used in the UI
    folder: "_posts/businesses" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "businessesData"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Store", name: "store", widget: "list", allow_add: true
      fields:
        - {label: "Status", name: "status", widget: "boolean"}
        - {label: "Location", name: "status", widget: "string"}
        - {label: "Maps Link", name: "status", widget: "string"}
        - {label: "Store Front", name: "store front image", widget: "image"}
        - {label: "Telephone", name: "telephone", widget: "string"}
        - {label: "Website", name: "website", widget: "string"}
        - {label: "Info", name: "Info", widget: "string"}
      }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}